---
- hosts: remote_hosts
  tasks:

  - name: Creates directory apache
    file:
      path: /home/ec2-user/apache/source
      state: directory 
      recurse: yes

  - name: Creates directory apache tmp
    file:
      path: /home/ec2-user/apache/tmp
      state: directory 
      recurse: yes

  - name: Download source files
    get_url:
      url: http://apache.cp.if.ua//httpd/httpd-2.2.34.tar.gz
      dest: /home/ec2-user/apache/source

  - name: Unarchive httpd-2.2.34.tar.gz
    unarchive: 
      src: /home/ec2-user/apache/source/httpd-2.2.34.tar.gz
      dest: /home/ec2-user/apache
      remote_src: yes
      
  - name: Configuring apache files
    command: /home/ec2-user/apache/httpd-2.2.34/configure 
    args:
      chdir: /home/ec2-user/apache/tmp
    
  - name: Making apache
    make:
      chdir: /home/ec2-user/apache/tmp
    become: true

  - name: Installing apache
    make:
      chdir: /home/ec2-user/apache/tmp
      target: install
    become: true

  - name: Start apache 
    command: /usr/local/apache2/bin/apachectl start
    become: true
   

 
